### ISSUE TITLE
Kotlin example

### ISSUE THREAD

**Issue by binkley** [openblockchains/awesome-blockchains#10]
This repo is 2 years old as I write this issue, so I'm unsure if you're taking contributions.

I'm happy to provide a code example in Kotlin.

**Comment by geraldb** [comment]
@binkley   Yes, it's alive and kicking. A Kotlin (blockchain) code example is more than welcome. Please, do add it. Prosit 2020! Happy new year. Cheers.

**Comment by binkley** [comment]
@geraldb If you wouldn't mind reviewing?  I followed the Ruby example:  https://github.com/binkley/awesome-blockchains/tree/master/blockchain.kt

If this seems like the right direction to you, I'll add examples for proof of work and transactions, and then issue a PR against this repo.

Cheers

**Comment by geraldb** [comment]
@binkley  That looks wonderful.  No worries about the lines of code. More important is clarity. Thanks for your efforts. Please, do. Please, continue.  Cheers. Prost.
