### ISSUE TITLE
FYI -- more sophisticated Kotlin implementation

### ISSUE THREAD

**Issue by binkley** [openblockchains/awesome-blockchains#13]
After a series of emails with a CS prof friend of mine, I've made a more sophisticated Kotlin version of blockchain.  My last challenge is to produce a true Merkle tree (which I haven't, yet).

https://github.com/binkley/spikes/tree/master/kotlin-blockchain

It seems out of scope for this repo, but I thought I'd pass it along to you.  (I'm using GitHub issues to communicate with you; I hope that's ok.)

**Comment by geraldb** [comment]
Thanks for highlighting and your contribution. I added your comments and link to the repo to the blockchain.kt page, 
see <https://github.com/openblockchains/awesome-blockchains/tree/master/blockchain.kt#bonus>  Keep it up. Cheers.
